# -----------------------
# DARO full robot params
# -----------------------

ndjson_bridge_node:
  ros__parameters:
    port: "/dev/ttyUSB0"
    baud: 115200

tof_to_range_node:
  ros__parameters:
    rx_topic: "/esp32/rx_json/tof"
    pub_topic: "/tof/range"
    frame_id: "tof_link"
    tof_min_range_m: 0.035
    tof_max_range_m: 4.0
    tof_fov_rad: 0.26
    use_ros_time: true

imu_json_node:
  ros__parameters:
    rx_topic: "/esp32/rx_json/sens"
    pub_topic: "/imu/data_raw"
    frame_id: "imu_link"
    use_ros_time: true

enc_json_node:
  ros__parameters:
    rx_topic: "/esp32/rx_json/enc"
    pub_topic: "/wheel/joint_states"
    use_ros_time: true
    left_joint: "left_wheel_joint"
    right_joint: "right_wheel_joint"
    ticks_per_rev: 660.0

joy_buttons_node:
  ros__parameters:
    # placeholders for now:
    deadman_button: 4
    turbo_button: 5