tof_to_range_node:
  ros__parameters:
    rx_topic: "/esp32/rx_json/tof"
    pub_topic: "/tof/range"
    frame_id: "tof_link"

    tof_min_range_m: 0.035
    tof_max_range_m: 0.35
    tof_fov_rad: 0.26
    use_ros_time: true