services:
  piper:
    image: lscr.io/linuxserver/piper:latest
    container_name: piper
    environment:
      - TZ=Etc/UTC
      - PIPER_VOICE=en_GB-northern_english_male-medium
    volumes:
      - ./piper-data:/config
    ports:
      - 10200:10200
    restart: unless-stopped